### ISSUE TITLE
removal captcha solver as not work

### ISSUE THREAD

**Issue by Krtuyi** [Skuxblan/Outlook-account-creator#2]
We hope this message finds you well. We kindly request the removal of CapSolver from your software at your earliest convenience. Your cooperation in this matter is greatly appreciated.

Thank you for your understanding and assistance.

**Comment by Skuxblan** [comment]
Thanks for you feedback. I will try to replace capsolver with something else as soon as I can.

**Comment by Skuxblan** [comment]
I can confirm CapSolver is replaced with other free solution - nopecha.

> We hope this message finds you well. We kindly request the removal of CapSolver from your software at your earliest convenience. Your cooperation in this matter is greatly appreciated.
> 
> Thank you for your understanding and assistance.

I can confirm CapSolver is replaced with other free solution - nopecha.
